name: Keep GitHub cron jobs alive

on:
  schedule:
    - cron: '30 1 * * *'

jobs:

  keepalive:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Keep GitHub cron jobs alive using dummy commits
        uses: gautamkrishnar/keepalive-workflow@v1
