name: Release

on:

  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:
    inputs:
      PRE_RELEASE:
        description: Set release type to pre-release
        type: boolean
        required: false
        default: false

jobs:

  release:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate rules
      run: ./generate.sh

    - name: Set variables
      run: |
        echo "RELEASE_NAME=$(date --utc '+%Y%m%d%H%M')" >> "$GITHUB_ENV"
        echo "RELEASE_DATE=$(date --utc '+%F %T %Z')" >> "$GITHUB_ENV"

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.RELEASE_NAME }}
        body: Updated on ${{ env.RELEASE_DATE }}
        artifacts: output/*

    - name: Delete old releases
      uses: dev-drprasad/delete-older-releases@v0.3.2
      with:
        keep_latest: 7
        delete_tags: true
      if: ${{ ! inputs.PRE_RELEASE }}
